// OrderManagerStyles.js
export const styles = {
  statsContainer: {
    display: "flex",
    background: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    padding: "16px 24px",
    marginBottom: "24px",
    alignItems: "center",
  },
  statItem: { display: "flex", flexDirection: "column", gap: "2px" },
  statDivider: {
    width: "1px",
    height: "32px",
    background: "#e2e8f0",
    margin: "0 30px",
  },
  statLabel: {
    fontSize: "0.75rem",
    color: "#64748b",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  statValue: { fontSize: "1.25rem", fontWeight: "700", color: "#0f172a" },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
    flexWrap: "wrap",
    gap: "12px",
  },
  filterGroup: { display: "flex", gap: "8px", flexWrap: "wrap" },

  // Tab Switcher Styles
  tabContainer: {
    display: "flex",
    gap: "1px",
    background: "#e2e8f0",
    padding: "4px",
    borderRadius: "8px",
    marginBottom: "20px",
    width: "fit-content",
  },
  tabBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    borderRadius: "6px",
    border: "none",
    fontSize: "0.85rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  activeTab: {
    background: "white",
    color: "#0f172a",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  inactiveTab: { background: "transparent", color: "#64748b" },

  filterBtn: {
    border: "1px solid",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "0.85rem",
    cursor: "pointer",
    fontWeight: "500",
  },
  searchWrapper: {
    display: "flex",
    alignItems: "center",
    background: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    padding: "6px 12px",
    width: "280px",
  },
  inputReset: {
    border: "none",
    outline: "none",
    background: "transparent",
    width: "100%",
    fontSize: "0.9rem",
  },
  exportBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "white",
    color: "#64748b",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    padding: "6px 16px",
    fontSize: "0.85rem",
    fontWeight: "600",
    cursor: "pointer",
    height: "36px",
    transition: "all 0.1s ease",
  },
  tableContainer: { display: "flex", flexDirection: "column", gap: "12px" },
  emptyState: { padding: "40px", textAlign: "center", color: "#64748b" },
  orderRow: {
    background: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    overflow: "hidden",
  },
  rowHeader: {
    padding: "16px",
    display: "flex",
    alignItems: "center",
    gap: "16px",
    cursor: "pointer",
  },
  colInfo: { flex: 1 },
  primaryText: { fontWeight: "600", color: "#0f172a", fontSize: "0.95rem" },
  metaText: { fontSize: "0.8rem", color: "#94a3b8", marginTop: "4px" },
  colStatus: { width: "120px", textAlign: "center" },
  badge: {
    fontSize: "0.75rem",
    padding: "4px 10px",
    borderRadius: "4px",
    border: "1px solid",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  colTotal: {
    width: "100px",
    textAlign: "right",
    fontWeight: "700",
    color: "#0f172a",
  },
  actionIconBtn: {
    background: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
    color: "#ef4444",
    cursor: "pointer",
    padding: "8px",
    marginLeft: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.1s",
  },
  iconBtn: {
    background: "transparent",
    border: "none",
    color: "#64748b",
    cursor: "pointer",
    padding: "4px",
  },
  expandedPanel: {
    background: "#f8fafc",
    borderTop: "1px solid #e2e8f0",
    padding: "24px",
  },
  panelGrid: { display: "grid", gridTemplateColumns: "2fr 1fr", gap: "24px" },
  customerGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "15px",
    background: "white",
    padding: "15px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
  },
  customerItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "0.9rem",
    color: "#334155",
  },
  noteBubble: {
    background: "#eff6ff",
    padding: "4px 8px",
    borderRadius: "20px",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  noteText: {
    fontSize: "0.7rem",
    fontWeight: "600",
    color: "#2563eb",
    textTransform: "uppercase",
  },
  noteInput: {
    flex: 1,
    padding: "10px",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    fontSize: "0.9rem",
    fontFamily: "inherit",
    resize: "vertical",
  },
  saveNoteBtn: {
    background: "#0f172a",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "0 16px",
    fontWeight: "600",
    cursor: "pointer",
    fontSize: "0.85rem",
  },
  sectionTitle: {
    fontSize: "0.75rem",
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    marginBottom: "10px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  itemsTable: {
    background: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    overflow: "hidden",
  },
  tableHeader: {
    display: "flex",
    padding: "8px 16px",
    background: "#f1f5f9",
    fontSize: "0.75rem",
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  itemRow: {
    display: "grid",
    gridTemplateColumns: "50px 1fr 80px",
    padding: "12px 16px",
    borderBottom: "1px solid #f1f5f9",
    fontSize: "0.9rem",
    alignItems: "center",
  },
  itemQty: { color: "#64748b", fontWeight: "500" },
  itemInfo: { display: "flex", flexDirection: "column" },
  itemName: { fontWeight: "500", color: "#334155" },
  variantLabel: {
    fontSize: "0.75rem",
    color: "#64748b",
    fontWeight: 600,
    marginTop: 2,
  },
  itemPrice: { fontWeight: "600", color: "#0f172a", textAlign: "right" },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "10px 16px",
    background: "#f8fafc",
    fontWeight: "600",
    fontSize: "0.9rem",
    color: "#64748b",
  },
  input: {
    padding: "8px",
    borderRadius: "4px",
    border: "1px solid #cbd5e1",
    fontSize: "0.85rem",
    width: "100%",
  },
  saveBtn: {
    background: "#0f172a",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "8px 12px",
    fontSize: "0.85rem",
    cursor: "pointer",
    fontWeight: "600",
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  cancelBtn: {
    background: "white",
    color: "#64748b",
    border: "1px solid #cbd5e1",
    borderRadius: "4px",
    padding: "8px 12px",
    fontSize: "0.85rem",
    cursor: "pointer",
    flex: 1,
  },
  secondaryBtn: {
    width: "100%",
    padding: "8px",
    background: "white",
    border: "1px solid #cbd5e1",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.85rem",
    marginTop: 8,
  },
  actionBtn: {
    background: "white",
    border: "1px solid #cbd5e1",
    color: "#0f172a",
    borderRadius: "4px",
    padding: "6px 12px",
    fontSize: "0.8rem",
    cursor: "pointer",
    fontWeight: "500",
    transition: "all 0.1s hover",
  },
  trackingBox: {
    padding: "10px",
    background: "#f1f5f9",
    borderRadius: "4px",
    textAlign: "center",
    fontSize: "0.9rem",
  },
  trackingLink: {
    color: "#2563eb",
    textDecoration: "none",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
  },
  toast: {
    position: "fixed",
    bottom: "24px",
    right: "24px",
    background: "#10b981",
    color: "white",
    padding: "12px 20px",
    borderRadius: "8px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: "500",
    zIndex: 100,
  },
  label: {
    fontSize: "0.75rem",
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: "8px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  detailCol: { display: "flex", flexDirection: "column" },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    backdropFilter: "blur(2px)",
  },
  modalContent: {
    background: "white",
    padding: "24px",
    borderRadius: "12px",
    width: "100%",
    maxWidth: "400px",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "12px",
  },
  modalTitle: {
    fontSize: "1.1rem",
    fontWeight: "600",
    color: "#0f172a",
    margin: 0,
  },
  modalMessage: { color: "#64748b", marginBottom: "24px", lineHeight: "1.5" },
  modalActions: { display: "flex", gap: "12px", justifyContent: "flex-end" },
  modalCancel: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    background: "white",
    color: "#64748b",
    cursor: "pointer",
    fontWeight: "500",
  },
  modalConfirm: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "none",
    background: "#0f172a",
    color: "white",
    cursor: "pointer",
    fontWeight: "500",
  },
  modalDelete: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "none",
    background: "#ef4444",
    color: "white",
    cursor: "pointer",
    fontWeight: "500",
  },
};
